name: Max3 内核编译
on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 检出源码
        uses: actions/checkout@v4
        with:
          ref: MIUI-OC-P
          fetch-depth: 0

      - name: 安装依赖
        run: sudo apt update && sudo apt install -y git bc bison flex libssl-dev make zip

      - name: 下载Clang
        run: git clone --depth=1 https://github.com/Black-Seraph/clang-14 clang

      - name: 编译内核
        run: |
          export ARCH=arm64
          make O=out nitrogen_user_defconfig
          make O=out -j$(nproc)

      - name: 打包卡刷包
        run: |
          git clone --depth=1 https://github.com/osm0sis/AnyKernel3
          cp out/arch/arm64/boot/Image.gz AnyKernel3/
          cd AnyKernel3
          zip -r9 Max3_Kernel.zip *

      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: Max3_Kernel_Ready
          path: AnyKernel3/Max3_Kernel.zip
